### ISSUE TITLE
Facebook icon wordt fout weergegeven

### ISSUE THREAD

**Issue by thomasdewulf** [FOSDeKangoeroes/KangoeroeWebsite#5]
Op dekangoeroes.be/html/contact.php

**Comment by thomasdewulf** [comment]
@Moeflon, @IanSchillewaert , @arnegoeteyn  help

**Comment by arnegoeteyn** [comment]
Waar precies

**Comment by thomasdewulf** [comment]
dekangoeroes.be/html/contact.php
<img width="1331" alt="schermafdruk 2016-12-15 21 40 14" src="https://cloud.githubusercontent.com/assets/10937597/21241270/2707ee82-c30f-11e6-90f5-31945d5f9b91.png">

**Comment by Moeflon** [comment]
Komt door de `display: inline-block;` op de `li`. Als je dat weglaat is het opgelost maar dan is er een bolletje voor. Gewoon `list-style: none;` doen op de `ul` is ook geen oplossing blijkbaar...

**Comment by arnegoeteyn** [comment]
Is het niet >list-style-type:none;

**Comment by arnegoeteyn** [comment]
Haha markdownpro

**Comment by arnegoeteyn** [comment]
Jullie begrijpen me wel

**Comment by Moeflon** [comment]
Shouldn't matter. Doet hetzelfde maar zonder de `-type` kan je er de kleur direct bij geven ook, a la `background` vs `background-image`, gewoon een shortcut dus.

Als hacky solution misschien gewoon op de 
`.company-social a i` een `line-height: 40px;` gooien? Who needs pixel-perfect anyways

**Comment by thomasdewulf** [comment]
IT AINT WORKING

<img width="1680" alt="schermafdruk 2016-12-15 21 50 40" src="https://cloud.githubusercontent.com/assets/10937597/21241590/92f075d2-c310-11e6-9160-15969bb9584e.png">

**Comment by thomasdewulf** [comment]
vic zijn hack werkt. Ligt ook aan het feit dat .fa een line-height van 1 krijgt in font-awesome.css.

**Comment by arnegoeteyn** [comment]
Boi skip die site gewoon, the future is text-based!!!!!

**Comment by thomasdewulf** [comment]
Hahahaha

**Comment by arnegoeteyn** [comment]
Nee met webshit kan ik echt nie helpen
